version: '3'
services:
  backend:
    container_name: transcendence-backend
    image: transcendence-backend
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    networks:
      - nestjs-network
    depends_on:
      - db
    working_dir: /app/backend
    volumes:
      - ./:/app/backend
      - /app/backend/node_modules
    restart: unless-stopped

  db:
    container_name: postgres
    image: postgres:latest
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    networks:
      - nestjs-network
    restart: unless-stopped
    ports:
      - 5432:5432

networks:
  nestjs-network:

volumes:
  postgres:
