version: '3'
services:
  frontend:
    container_name: transcendence-frontend
    image: transcendence-frontend
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - ${DOMAIN}:3001:3001
    env_file:
      - .env
    networks:
      - nestjs-network
    depends_on:
      - postgres
    working_dir: /app/frontend
    volumes:
      - frontend:/app/frontend
      - node_modules_f:/app/frontend/node_modules
    restart: unless-stopped
    
  backend:
    container_name: transcendence-backend
    image: transcendence-backend
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - ${DOMAIN}:3000:3000
      - ${DOMAIN}:5555:5555
    env_file:
      - .env
    networks:
      - nestjs-network
    depends_on:
      - postgres
    working_dir: /app/backend
    volumes:
      - backend:/app/backend
      - node_modules_b:/app/backend/node_modules
    restart: unless-stopped

  postgres:
    container_name: postgres
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
       - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - nestjs-network
    restart: unless-stopped

networks:
  nestjs-network:

volumes:
  node_modules_b:
  node_modules_f:
  postgres:
  backend:
    driver: local
    driver_opts:
      type: none
      device: ./${PWD}/backend
      o: bind
  frontend:
    driver: local
    driver_opts:
      type: none
      device: ./${PWD}/frontend
      o: bind