version: '3'
services:
  backend:
    container_name: transcendence-backend
    image: transcendence-backend
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - 3000:3000
      - 5555:5555
    networks:
      - nestjs-network
    depends_on:
      - postgres
    working_dir: /app/backend
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules
    restart: unless-stopped

  postgres:
    container_name: postgres
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    # ports:
    #   - 5432:5432
    networks:
      - nestjs-network
    restart: unless-stopped

networks:
  nestjs-network:

volumes:
  postgres:
